# Generated by Django 4.2.7 on 2023-11-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EduTerm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseterm',
            name='teacher',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_teacher', True)), on_delete=django.db.models.deletion.PROTECT, related_name='course_terms', to=settings.AUTH_USER_MODEL, verbose_name='استاد'),
        ),
        migrations.AddField(
            model_name='courseterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_terms', to='EduTerm.term', verbose_name='ترم'),
        ),
    ]
