# Generated by Django 4.2.7 on 2023-11-22 08:12

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTerm', '0003_term_active_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='exam_start_date',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name=' تاریخ شروع امتحان\u200cها'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_end_date',
            field=django_jalali.db.models.jDateField(blank=True, verbose_name='پایان ترم'),
        ),
    ]
