# Generated by Django 4.2.7 on 2023-11-28 16:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('EduTerm', '0006_alter_term_exam_start_date_alter_term_term_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='exam_start_date',
            field=django_jalali.db.models.jDateField(verbose_name=' تاریخ شروع امتحان\u200cها'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term_end_date',
            field=django_jalali.db.models.jDateField(verbose_name='پایان ترم'),
        ),
    ]
