version: '3'

services:
  db:
    image: postgres:14
    env_file:
      - .env.production
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: runserver
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery
    env_file:
      - .env.production
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  media_volume:
