# Generated by Django 4.2.7 on 2023-11-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EduBase', '0001_initial'),
        ('Identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='EduBase.college', verbose_name='دانشکده'),
        ),
        migrations.AddField(
            model_name='user',
            name='edu_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='EduBase.edufield', verbose_name='رشته تحصیلی'),
        ),
    ]
