# Generated by Django 4.2.7 on 2023-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, 'تعیین نشده'), (1, 'مرد'), (2, 'زن')], default=0, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='military_service',
            field=models.IntegerField(blank=True, choices=[(0, 'تعیین نشده'), (1, 'کارت پایان خدمت'), (2, 'معافیت پزشکی'), (3, 'معافیت غیرپزشکی'), (4, 'معافیت تحصیلی'), (5, 'در حال خدمت')], default=0, null=True, verbose_name='وضعیت نظام وظیفه'),
        ),
    ]
