# Generated by Django 4.2.7 on 2023-11-09 20:02

import Identity.models
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0004_alter_user_managers_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Identity.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='تاریخ تولد'),
        ),
    ]
