# Generated by Django 4.2.7 on 2023-11-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0005_alter_user_managers_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'national_code')},
        ),
    ]
