# Generated by Django 4.2.7 on 2023-11-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0006_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_it_manager',
            field=models.BooleanField(default=False, verbose_name='مدیر آی تی است'),
        ),
    ]
