# Generated by Django 4.2.7 on 2023-11-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Identity', '0007_alter_user_is_it_manager'),
        ('Identity', '0007_user_unique_code_alter_user_is_it_manager'),
    ]

    operations = [
    ]
