# Generated by Django 4.2.7 on 2023-11-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_certificate_place', models.CharField(max_length=128, verbose_name='محل صدور گواهی')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_description', models.TextField(verbose_name='توضیحات درخواست')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('status', models.IntegerField(choices=[(1, 'پذیرش'), (2, 'رد شده'), (3, 'در حال بررسی')], verbose_name='وضعیت')),
                ('has_academic_year', models.BooleanField(default=False, verbose_name='دارای سنوات تحصیلی')),
                ('request_type', models.IntegerField(choices=[(1, 'درخواست حذف و اضافه'), (2, 'درخواست اشتغال به تحصیل'), (3, 'درخواست ثبت نام'), (4, 'درخواست تجدید نظر'), (5, 'درخواست حذف ترم'), (6, 'درخواست حذف اضطراری دانشجو')], verbose_name='نوع درخواست')),
            ],
        ),
    ]
