# Generated by Django 4.2.7 on 2023-11-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EduTerm', '0001_initial'),
        ('EduRequest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_requests', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_requests', to='EduTerm.term', verbose_name='ترم'),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='user_answer',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_teacher', True), ('is_chancellor', True), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='student_request_answers', to=settings.AUTH_USER_MODEL, verbose_name='توضیحات معاون آموزشی'),
        ),
        migrations.AddField(
            model_name='enrollmentcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_certificates', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='enrollmentcertificate',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_certificates', to='EduTerm.term', verbose_name='ترم تحصیلی'),
        ),
    ]
