# Generated by Django 4.2.7 on 2023-11-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduRequest', '0006_alter_studentrequest_status'),
        ('EduRequest', '0007_alter_enrollmentcertificate_enrollment_certificate_place'),
    ]

    operations = [
    ]
