# Generated by Django 4.2.7 on 2023-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduRequest', '0008_merge_20231128_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentcertificate',
            name='enrollment_certificate_place',
            field=models.CharField(default=None, max_length=128, verbose_name='محل صدور گواهی'),
        ),
    ]
