# Generated by Django 4.2.7 on 2023-11-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduRequest', '0009_alter_enrollmentcertificate_enrollment_certificate_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'پذیرش'), (2, 'رد شده'), (3, 'در حال بررسی')], default=None, verbose_name='وضعیت'),
        ),
    ]
