# Generated by Django 4.2.7 on 2023-11-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EduEnroll', '0002_initial'),
        ('EduTerm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_courses', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_student', True)), on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_students', to=settings.AUTH_USER_MODEL, verbose_name='دانشجو'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='teacher_assistant',
            field=models.ForeignKey(limit_choices_to=models.Q(('is_teacher', True)), on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_teacher_assistants', to=settings.AUTH_USER_MODEL, verbose_name='استاد راهنما'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='EduTerm.term', verbose_name='ترم'),
        ),
    ]
