# Generated by Django 4.2.7 on 2023-11-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduEnroll', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='taken_term_number',
            field=models.IntegerField(verbose_name='تعداد ترم گذرانده'),
        ),
    ]
