# Generated by Django 4.2.7 on 2023-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduEnroll', '0004_alter_enrollment_taken_term_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.IntegerField(choices=[(1, 'ثبت نام کرده'), (2, 'حذف شده'), (3, 'کامل شده'), (4, 'تایید شده')], verbose_name='وضعیت'),
        ),
    ]
